name: Contrast local scan

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
    - '*'
    - '!main'

permissions:
  contents: read
  checks: write

jobs:
  validate-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses : Contrast-Security-OSS/contrast-local-scan-action@checks
        name: Run action against repoository
        with:
          apiUrl: ${{ secrets.CONTRAST__API__URL }}
          apiUserName: ${{ secrets.CONTRAST__API__USER_NAME }}
          apiKey: ${{ secrets.CONTRAST__API__API_KEY }}
          apiServiceKey: ${{ secrets.CONTRAST__API__SERVICE_KEY }}
          apiOrgId: ${{ secrets.CONTRAST__API__ORGANIZATION }}
          checks: true
          severity: critical
